#!/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

KIVITENDO_VERSION="3.5.3"

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MUNIN_PLUGINS="
"

echo "* Activate munin plugins"
/usr/local/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Get latest"
apt-get -y update
apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Install kivitendo"
mkdir -p /usr/local/src/kivitendo_documents
cd /usr/local/src/
chown -R www-data:staff kivitendo_documents
git clone https://github.com/kivitendo/kivitendo-erp.git
cd kivitendo-erp
git checkout -b release-${KIVITENDO_VERSION}
mkdir webdav
chown -R www-data users spool webdav templates
mv /usr/local/var/tmp/kivitendo.conf config/kivitendo.conf
cp scripts/boot/systemd/kivitendo-task-server.service /etc/systemd/system/
sed -i \
     -e "s#/var/www/kivitendo-erp/scripts/task_server.pl#/usr/local/src/kivitendo-erp/scripts/task_server.pl#" \
     /etc/systemd/system/kivitendo-task-server.service
systemctl daemon-reload
cpanm HTML::Restrict

echo "* Install kivitendo-api"
addgroup ruby
adduser --disabled-password --system --quiet --home /home/ruby ruby
adduser ruby ruby
mkdir -p /home/ruby/www/
cd /home/ruby/www/
git clone https://github.com/jfqd/kivitendo_rest_api.git
cd kivitendo_rest_api
gem install bundler
export RAILS_ENV=production
bundle install
rm config/secrets.yml config/secrets.yml.enc config/secrets.yml.key || true
mv config/secrets.yml.bak config/secrets.yml
RAILS_SECRET=$(bundle exec rails secret)
sed -i \
     -e "s/enter-secret_key_base-here/${RAILS_SECRET}/" \
     config/secrets.yml
sed -i \
     -e "s/config.read_encrypted_secrets = true/config.read_encrypted_secrets = false/" \
     config/environments/production.rb
chown -R ruby:ruby /home/ruby
cp /usr/local/var/tmp/kivitendo-api.service /etc/systemd/system/kivitendo-api.service
systemctl daemon-reload

echo "* Activate apache modules"
a2enmod fcgid  || true
a2enmod dav    || true
a2enmod dav_fs || true
sed -i -e "s/Listen 80/Listen 8080/" /etc/apache2/ports.conf
systemctl restart apache2

echo "* Setup nginx"
mv /usr/local/var/tmp/kivitendo /etc/nginx/sites-available/kivitendo
ln -nfs /etc/nginx/sites-available/kivitendo /etc/nginx/sites-enabled/kivitendo
mkdir -p /etc/nginx/ssl
chmod 0500 /etc/nginx/ssl
/usr/local/bin/ssl-selfsigned.sh -d /etc/nginx/ssl -f kivitendo
systemctl restart nginx

echo "* Setup postgresql"
sed -i \
    -e "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/" \
    /etc/postgresql/9.6/main/postgresql.conf
echo "local all kivitendo password" >> /etc/postgresql/9.6/main/pg_hba.conf
echo "host all kivitendo 127.0.0.1 255.255.255.255 password" >> /etc/postgresql/9.6/main/pg_hba.conf
mv /usr/local/var/tmp/psql_kivi_user.sql /usr/local/src/kivitendo-erp/config/psql_kivi_user.sql
systemctl restart postgresql

echo "* Setup postgresql backup"
mkdir -p /var/lib/postgresql/backups
chown postgres:postgres /var/lib/postgresql/backups
echo "0 1 * * * /usr/local/bin/psql_backup" > /var/spool/cron/crontabs/postgres
chown postgres:crontab /var/spool/cron/crontabs/postgres

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
apt-get -y purge git make gcc g++ build-essential
rm -rf /usr/local/var/tmp/*
history -c
