Listen 127.0.0.1:8080
<VirtualHost 127.0.0.1:8080>
  AddHandler fcgid-script .fpl
  AliasMatch ^/[^/]+\.pl /usr/local/src/kiwifrei-erp/dispatcher.fpl

  Alias /icons  /usr/share/apache2/icons
  Alias /dav    /usr/local/src/kiwifrei-erp/templates/latex-druckvorlage/firma
  Alias /       /usr/local/src/kiwifrei-erp/

  FcgidMaxRequestLen 10485760
  
  DavLockDB /usr/local/src/dav-lock/DavLock

  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

  <Directory /usr/local/src/kiwifrei-erp>
    AllowOverride All
    Options ExecCGI Includes FollowSymlinks
    Require all granted
  </Directory>

  <DirectoryMatch /usr/local/src/kiwifrei-erp/users>
    Require all denied
  </DirectoryMatch>
  
  <Location /dav>
    Options Indexes
    ForceType text/plain
    DAV On
    AuthType Basic
    AuthName "webdav"
    AuthUserFile /etc/apache2/webdav.password
    Require valid-user
    DirectoryIndex disabled
    Options FollowSymlinks
  </Location>
  
  RewriteEngine On
  RewriteRule .*(\.git|config).*$ - [F,NC]
</VirtualHost>