resolver 10.10.10.10:53 valid=30s;

upstream backend {
  server 127.0.0.1:8080;
}

server {
  listen 80;
  server_name _;
  return 301 https://$server_name$request_uri;
}

server {
  listen               443 http2 ssl;
  server_name          _;

  access_log           /var/log/nginx/kiwifrei.access.log main;
  error_log            /var/log/nginx/kiwifrei.error.log;

  ssl_certificate      /etc/apache2/ssl/kiwifrei.crt;
  ssl_certificate_key  /etc/apache2/ssl/kiwifrei.key;
  ssl_protocols        TLSv1.2 TLSv1.3;
  ssl_ciphers          ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;
  ssl_session_cache    shared:SSL:10m;
  ssl_session_timeout  10m;

  client_max_body_size 25M;

  add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
  add_header X-Frame-Options "sameorigin";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options nosniff;
  add_header Referrer-Policy strict-origin-when-cross-origin;
  add_header Permissions-Policy "interest-cohort=(), geolocation=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=()";

  set $upstream_authelia https://auth.example.com/api/authz/auth-request;
  
  location ^~ /js {
    root /usr/local/src/kiwifrei-erp;
  }

  location ^~ /css {
    root /usr/local/src/kiwifrei-erp;
  }

  location ^~ /image {
    root /usr/local/src/kiwifrei-erp;
  }
  
  location /backup {
    auth_basic           "Backup area";
    auth_basic_user_file /etc/apache2/webdav.password;
    alias                "/var/lib/postgresql/backups/";
    autoindex            on;
  }

  location /dav {
    proxy_pass http://backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # location ^~ /(\.git|\.gitignore|.env|bin|config|Devel|locale|menus|modules|scripts|SL|sql|t|users)/ {
  #   deny all;
  # }

  location /auth {
    internal;
    proxy_pass $upstream_authelia;

    proxy_set_header X-Original-Method $request_method;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Content-Length "";
    proxy_set_header Connection "";

    proxy_pass_request_body off;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    proxy_redirect http:// $scheme://;
    proxy_http_version 1.1;
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;
    client_body_buffer_size 128k;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
  }

  location / {
    proxy_pass http://backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    auth_request /auth;

    auth_request_set $user $upstream_http_remote_user;
    auth_request_set $groups $upstream_http_remote_groups;
    proxy_set_header X-Kiwifrei-Auth-User $user;
    proxy_set_header X-Kiwifrei-Client-ID $groups;
    proxy_set_header X-Kiwifrei-App-Secret SECURE_PROXY_SECRET;

    auth_request_set $redirection_url $upstream_http_location;
    error_page 401 =302 $redirection_url;
  }
}

server {
  listen 127.0.0.1;
  server_name localhost;
  location /nginx_status {
    stub_status on;
    access_log   off;
    allow 127.0.0.1;
    deny all;
  }
}